[project]
name = "DLC-Stacks"
authors = []
description = ""
telemetry = false
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[project.cache_location]
path = ".requirements"

# Unified Contract
[contracts.dlc-manager-priced-v0-1]
path = "contracts/dlc-manager.clar"

[contracts.sample-contract-loan-v0-1]
path = "examples/sample-contract-loan.clar"

[contracts.dlc-link-callback-trait-v2]
path = "contracts/dlc-link-callback-trait.clar"

# USDLC for testing
[contracts.dlc-stablecoin]
path = 'contracts/dlc-stablecoin.clar'
clarity_version = 1
epoch = 2.0

[contracts.callback-contract]
path = "tests/callback-contract-mock.clar"

# Arkadiko requirements
# [[project.requirements]]
# contract_id = "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-stake-pool-diko-trait-v1"
# [[project.requirements]]
# contract_id = "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-stake-registry-trait-v1"
# [[project.requirements]]
# contract_id = "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-stake-pool-trait-v1"
[[project.requirements]]
contract_id = "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-dao-token-trait-v1"

# # Arkadiko contracts
# [contracts.arkadiko-dao]
# path = "examples/arkadiko/arkadiko-dao.clar"

# [contracts.usda-token]
# path = "examples/arkadiko/usda-token.clar"

# [contracts.arkadiko-token]
# path = "examples/arkadiko/arkadiko-token.clar"

# [contracts.arkadiko-diko-guardian-v1-1]
# path = "examples/arkadiko/arkadiko-diko-guardian-v1-1.clar"

# [contracts.usda-pool-trait-v1-1]
# path = "examples/arkadiko/usda-pool-trait-v1-1.clar"

# [contracts.usda-loans-trait-v1-1]
# path = "examples/arkadiko/usda-loans-trait-v1-1.clar"

# [contracts.main]
# path = "examples/arkadiko/main.clar"

# [contracts.usda-pool-v1-1]
# path = "examples/arkadiko/usda-pool-v1-1.clar"

# [contracts.usda-loans-v1-1]
# path = "examples/arkadiko/usda-loans-v1-1.clar"

# Other settings
[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
