[project]
name = 'DLC-Stacks'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

# [[project.requirements]]
# contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[contracts.callback-contract-v1-1]
path = 'tests/callback-contract-mock.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-link-callback-trait-v1-1]
path = 'contracts/dlc-link-callback-trait.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-manager-trait-v1-2]
path = 'contracts/dlc-manager-trait.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-manager-v1-1]
path = 'contracts/dlc-manager.clar'
clarity_version = 2
epoch = 2.3

[contracts.dlc-stablecoin-v1-1]
path = 'contracts/dlc-stablecoin.clar'
clarity_version = 2
epoch = 2.3

[contracts.sample-contract-loan-v1-1]
path = 'examples/sample-contract-loan.clar'
clarity_version = 2
epoch = 2.3

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
