[project]
name = "DLC-Stacks"
authors = []
description = ""
telemetry = false
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify"

[project.cache_location]
path = ".requirements"

# Unified Contract
[contracts.dlc-manager-priced-v0-1]
path = "contracts/dlc-manager.clar"

[contracts.sample-contract-loan-v0-1]
path = "examples/sample-contract-loan.clar"

# Basic
[contracts.dlc-manager-basic-v0-1]
path = "legacy-contracts/basic/dlc-manager-basic.clar"

[contracts.sample-contract-basic-v0-1]
path = "legacy-contracts/basic/sample-protocol-contract.clar"

# Priced
[contracts.dlc-manager-priced-v0]
path = "legacy-contracts/priced/dlc-manager-priced.clar"

[contracts.sample-contract-priced-v0]
path = "legacy-contracts/priced/sample-protocol-contract.clar"

# Loan
[contracts.dlc-manager-loan-v0]
path = "legacy-contracts/loan/dlc-manager-loan.clar"

[contracts.sample-contract-loan-v0]
path = "legacy-contracts/loan/sample-protocol-contract.clar"

# Traits
[contracts.dlc-create-callback-trait]
path = "legacy-contracts/basic/dlc-create-callback-trait.clar"

[contracts.dlc-link-callback-trait]
path = "legacy-contracts/loan/dlc-link-callback-trait.clar"

[contracts.dlc-link-callback-trait-v2]
path = "contracts/dlc-link-callback-trait.clar"


# Other settings
[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
